version: '3.8'

services:
  service_lavagna_server:
    container_name: lavagna_server_pg
    build:
      context: .
      dockerfile: Dockerfile_lavagna
      args: # from env_file for image building
        PG_DIALECT: ${PG_DIALECT} 
        PG_CONNECTOR: ${PG_CONNECTOR}
        PG_PORT: ${PG_PORT}
        DB_NAME: ${DB_NAME}
        DB_LOGIN: ${DB_LOGIN}
        DB_PASS: ${DB_PASS}
        APP_MODE: ${APP_MODE}
    ports:
      - 80:8080
    depends_on:
      - service_lavagna_db

  service_lavagna_db:
    container_name: lavagna_db_pg
    build:
      context: .
      dockerfile: Dockerfile_postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_LOGIN}
      - POSTGRES_PASSWORD=${DB_PASS}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - lavagna_pg:/var/lib/postgresql/data 

networks:
  default:
    name: lavagna_net_pg

volumes:
  lavagna_pg:
    name: lavagna_vol_pg